export const variables = {
    BASE_URL: "https://lthshop.azurewebsites.net/api/",
    USER_API: "http://localhost:5049/api/Customers",
    PRODUCT_API: "http://localhost:5049/api/Products",
    ORDER_API: "http://localhost:5049/api/Orders",
    PRODUCTSIZE_API: "http://localhost:5049/api/Productsizes",
    ORDERITEM_API: "http://localhost:5049/api/OrderItems",
    CUSTOMER_API: "http://localhost:5049/api/Customers",
    AUTHEN_API: "http://localhost:5049/api/Authen",
    CART_API: "http://localhost:5049/api/Carts",
    CART_ITEM_API: "http://localhost:5049/api/CartItems",
    RECOMMENDATION_API_BUNDLE: "https://lthstore-recommeder-djdnaeh9eudkd4eu.southeastasia-01.azurewebsites.net/bundle-recommendations",
    RECOMMENDATION: "https://lthstore-recommeder-djdnaeh9eudkd4eu.southeastasia-01.azurewebsites.net/recommendations/",
    REVENUE_API: "http://localhost:5049/api/Revenues",
    HISTORYSTOCK_API: "http://localhost:5049/api/StockHistories",
}